version: "3.3"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    expose:
      - 9999
    ports:
      - 1337 

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "42069:42069"
      - "80:80"
